import { GENERATION_CONFIG, STORY_STRUCTURE } from '../../data/storyBible';

// Story configuration
export const TOTAL_CHAPTERS = STORY_STRUCTURE?.totalChapters || 12;
export const SUBCHAPTERS_PER_CHAPTER = STORY_STRUCTURE?.subchaptersPerChapter || 3;
export const MIN_WORDS_PER_SUBCHAPTER = GENERATION_CONFIG.wordCount.minimum; // 800 words
export const TARGET_WORDS = GENERATION_CONFIG.wordCount.target; // 900 words
export const DECISION_SUBCHAPTER = SUBCHAPTERS_PER_CHAPTER;
export const MAX_RETRIES = GENERATION_CONFIG.qualitySettings?.maxRetries || 1;

// Text truncation lengths for prompts and logging (in characters)
export const TRUNCATE_SUMMARY = 500; // For brief narrative summaries in prompts
export const TRUNCATE_VALIDATION = 3000; // For full narrative in validation contexts
export const TRUNCATE_DESCRIPTION = 300; // For thread/choice descriptions
export const TRUNCATE_PREVIEW = 100; // For short previews/logging

// ============================================================================
// PATH PERSONALITY SYSTEM - Tracks cumulative player behavior for coherent narrative
// ============================================================================
export const PATH_PERSONALITY_TRAITS = {
  // Maps choice patterns to narrative personality
  AGGRESSIVE: {
    keywords: ['confront', 'direct', 'immediate', 'force', 'demand', 'pressure'],
    narrativeStyle: 'Jack acts decisively, confronting obstacles head-on',
    dialogueTone: 'more direct and confrontational',
    riskTolerance: 'high',
  },
  METHODICAL: {
    keywords: ['investigate', 'gather', 'evidence', 'careful', 'plan', 'wait'],
    narrativeStyle: 'Jack proceeds cautiously, gathering information before acting',
    dialogueTone: 'more measured and analytical',
    riskTolerance: 'low',
  },
  BALANCED: {
    narrativeStyle: 'Jack balances intuition with evidence',
    dialogueTone: 'adapts to the situation',
    riskTolerance: 'moderate',
  },
};

// ============================================================================
// DECISION CONSEQUENCE REGISTRY - Tracks what each choice means for continuity
// ============================================================================
// Note: Chapter 1C decision consequences are now dynamically generated since 1C is LLM-generated.
// This registry is populated dynamically by _ensureDecisionConsequences() and _ensureDecisionConsequencesFast()
// when players make choices. The hardcoded entries below are fallback templates.
export const DECISION_CONSEQUENCES = {
  // Chapter 1 decision consequences - generated dynamically based on LLM output
  // The actual consequences depend on what 1C's decision options are (generated by LLM)
  // Fallback template for personality tracking (A = methodical, B = aggressive)
  '001C': {
    A: {
      immediate: 'Jack chose the methodical, evidence-focused approach',
      ongoing: ['More careful approach', 'More complete evidence trail', 'Slower but thorough investigation'],
      characterImpact: { trust: +10, aggression: -5, thoroughness: +15 },
    },
    B: {
      immediate: 'Jack chose the direct, confrontational approach',
      ongoing: ['More adversarial relationships', 'Faster revelation of threats', 'Higher personal risk'],
      characterImpact: { trust: -10, aggression: +15, thoroughness: -5 },
    },
  },
  // Additional chapter consequences are generated dynamically by the LLM
};

// ============================================================================
// THREAD NORMALIZATION - Prevents duplicate threads across paths
// Uses semantic similarity for fuzzy matching of equivalent threads
// ============================================================================

/**
 * Synonym groups for semantic thread matching
 * Verbs in the same group are treated as equivalent for deduplication
 */
export const VERB_SYNONYM_GROUPS = [
  // Meeting/Encounter synonyms
  ['meet', 'see', 'visit', 'rendezvous', 'encounter', 'come', 'arrive', 'show'],
  // Promise/Agreement synonyms
  ['promise', 'agree', 'commit', 'vow', 'swear', 'pledge', 'guarantee', 'assure'],
  // Investigation synonyms
  ['investigate', 'search', 'look', 'examine', 'check', 'probe', 'dig', 'explore'],
  // Confrontation synonyms
  ['confront', 'face', 'challenge', 'accuse', 'question', 'interrogate', 'press'],
  // Following/Tracking synonyms
  ['follow', 'track', 'tail', 'shadow', 'pursue', 'watch', 'observe', 'surveil'],
  // Communication synonyms
  ['call', 'phone', 'contact', 'reach', 'message', 'notify', 'inform', 'tell'],
  // Discovery synonyms
  ['find', 'discover', 'uncover', 'reveal', 'learn', 'realize', 'determine'],
  // Threat synonyms
  ['threaten', 'warn', 'intimidate', 'menace', 'pressure', 'coerce'],
];

/**
 * Location synonym groups for semantic matching
 */
export const LOCATION_SYNONYM_GROUPS = [
  ['docks', 'pier', 'wharf', 'harbor', 'waterfront', 'marina', 'port'],
  ['warehouse', 'building', 'factory', 'facility', 'plant'],
  ['office', 'room', 'study', 'workspace'],
  ['bar', 'pub', 'tavern', 'murphy', 'saloon'],
  ['prison', 'jail', 'greystone', 'cell', 'penitentiary'],
  ['alley', 'alleyway', 'backstreet', 'passage'],
  ['apartment', 'flat', 'residence', 'home', 'place'],
];
